#!/bin/sh
cd insol/n80
time /hom/geirkp/lagbouss/i386/knaai.new < indat 1> f.log 2> f.err
cd /home/info/SUP/geirkp/lagbouss/runexinsol

cd insol/n160
time /hom/geirkp/lagbouss/i386/knaai.new < indat 1> f.log 2> f.err
cd /home/info/SUP/geirkp/lagbouss/runexinsol

